name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, bcmath, pdo_mysql
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate app key
        run: php artisan key:generate --force

      - name: Prepare public folder for Azure
        run: |
          echo "<configuration><system.webServer><rewrite><rules><rule name='Laravel' stopProcessing='true'><match url='.*' /><conditions logicalGrouping='MatchAll'><add input='{REQUEST_FILENAME}' matchType='IsFile' negate='true' /><add input='{REQUEST_FILENAME}' matchType='IsDirectory' negate='true' /></conditions><action type='Rewrite' url='public/{R:0}' /></rule></rules></rewrite></system.webServer></configuration>" > web.config

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SkillSwap'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
